name: Update AI Agents News

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 feedparser newspaper3k

    - name: Run news update script
      env:
        BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
      run: python scripts/update_news.py

    - name: Commit and push if changes exist
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update AI agents news $(date +'%Y-%m-%d')" && git push)
